/* tslint:disable */
/* eslint-disable */
/**
 * Household Debt API
 * API to provide data for household debt information from data.gov
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface County {
    /**
     * County Name
     */
    'name': string;
    /**
     * County Fips Code
     */
    'fips_code': string;
}
export interface CountyDebt {
    /**
     * County
     */
    'county': string;
    /**
     * Average debt ratio
     */
    'average_debt': number;
    /**
     * FIPS code for the County
     */
    'fips_code': string;
}
export interface CountyExtended {
    /**
     * County Name
     */
    'name': string;
    /**
     * County Fips Code
     */
    'fips_code': string;
    /**
     * State Code for County
     */
    'state_code': string;
}
export interface Debt {
    /**
     * Date and time of debt
     */
    'date': string;
    /**
     * Lower bound of debt
     */
    'low': number;
    'high': number | null;
}
export interface DebtExtended {
    /**
     * Date and time of debt
     */
    'date': string;
    /**
     * Lower bound of debt
     */
    'low': number;
    'high': number | null;
    /**
     * County of Debt
     */
    'county': string;
    /**
     * State of County with Debt
     */
    'state': string;
    /**
     * FIPS code for the County
     */
    'fips_code': string;
}
export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface State {
    /**
     * State Name
     */
    'name': string;
    /**
     * State Code
     */
    'code': string;
    /**
     * State Fips Code
     */
    'fips_code': string;
}
export interface StateDebt {
    /**
     * State
     */
    'state': string;
    /**
     * Average debt ratio
     */
    'average_debt': number;
    /**
     * Number of Counties
     */
    'number_of_counties': number;
    /**
     * FIPS code for the State
     */
    'fips_code': string;
}
export interface ValidationError {
    'loc': Array<ValidationErrorLocInner>;
    'msg': string;
    'type': string;
}
export interface ValidationErrorLocInner {
}

/**
 * CountiesApi - axios parameter creator
 */
export const CountiesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all counties information
         * @summary Get all counties
         * @param {string | null} [name] 
         * @param {string | null} [fipsCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountiesCountiesGet: async (name?: string | null, fipsCode?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/counties`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (fipsCode !== undefined) {
                localVarQueryParameter['fips_code'] = fipsCode;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get specific county details
         * @summary Get county details
         * @param {string} fipsCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountyByFipsCountiesFipsCodeGet: async (fipsCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fipsCode' is not null or undefined
            assertParamExists('getCountyByFipsCountiesFipsCodeGet', 'fipsCode', fipsCode)
            const localVarPath = `/counties/{fips_code}`
                .replace(`{${"fips_code"}}`, encodeURIComponent(String(fipsCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get specific county debt details
         * @summary Get county debt
         * @param {string} fipsCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDebtByCountyFipsCountiesFipsCodeDebtGet: async (fipsCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fipsCode' is not null or undefined
            assertParamExists('getDebtByCountyFipsCountiesFipsCodeDebtGet', 'fipsCode', fipsCode)
            const localVarPath = `/counties/{fips_code}/debt`
                .replace(`{${"fips_code"}}`, encodeURIComponent(String(fipsCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CountiesApi - functional programming interface
 */
export const CountiesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CountiesApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all counties information
         * @summary Get all counties
         * @param {string | null} [name] 
         * @param {string | null} [fipsCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountiesCountiesGet(name?: string | null, fipsCode?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CountyExtended>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountiesCountiesGet(name, fipsCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountiesApi.getCountiesCountiesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get specific county details
         * @summary Get county details
         * @param {string} fipsCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountyByFipsCountiesFipsCodeGet(fipsCode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CountyExtended>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountyByFipsCountiesFipsCodeGet(fipsCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountiesApi.getCountyByFipsCountiesFipsCodeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get specific county debt details
         * @summary Get county debt
         * @param {string} fipsCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDebtByCountyFipsCountiesFipsCodeDebtGet(fipsCode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Debt>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDebtByCountyFipsCountiesFipsCodeDebtGet(fipsCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountiesApi.getDebtByCountyFipsCountiesFipsCodeDebtGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CountiesApi - factory interface
 */
export const CountiesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CountiesApiFp(configuration)
    return {
        /**
         * Get all counties information
         * @summary Get all counties
         * @param {CountiesApiGetCountiesCountiesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountiesCountiesGet(requestParameters: CountiesApiGetCountiesCountiesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<CountyExtended>> {
            return localVarFp.getCountiesCountiesGet(requestParameters.name, requestParameters.fipsCode, options).then((request) => request(axios, basePath));
        },
        /**
         * Get specific county details
         * @summary Get county details
         * @param {CountiesApiGetCountyByFipsCountiesFipsCodeGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountyByFipsCountiesFipsCodeGet(requestParameters: CountiesApiGetCountyByFipsCountiesFipsCodeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<CountyExtended> {
            return localVarFp.getCountyByFipsCountiesFipsCodeGet(requestParameters.fipsCode, options).then((request) => request(axios, basePath));
        },
        /**
         * Get specific county debt details
         * @summary Get county debt
         * @param {CountiesApiGetDebtByCountyFipsCountiesFipsCodeDebtGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDebtByCountyFipsCountiesFipsCodeDebtGet(requestParameters: CountiesApiGetDebtByCountyFipsCountiesFipsCodeDebtGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<Debt>> {
            return localVarFp.getDebtByCountyFipsCountiesFipsCodeDebtGet(requestParameters.fipsCode, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CountiesApi - interface
 */
export interface CountiesApiInterface {
    /**
     * Get all counties information
     * @summary Get all counties
     * @param {CountiesApiGetCountiesCountiesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCountiesCountiesGet(requestParameters?: CountiesApiGetCountiesCountiesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<CountyExtended>>;

    /**
     * Get specific county details
     * @summary Get county details
     * @param {CountiesApiGetCountyByFipsCountiesFipsCodeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCountyByFipsCountiesFipsCodeGet(requestParameters: CountiesApiGetCountyByFipsCountiesFipsCodeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<CountyExtended>;

    /**
     * Get specific county debt details
     * @summary Get county debt
     * @param {CountiesApiGetDebtByCountyFipsCountiesFipsCodeDebtGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDebtByCountyFipsCountiesFipsCodeDebtGet(requestParameters: CountiesApiGetDebtByCountyFipsCountiesFipsCodeDebtGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<Debt>>;

}

/**
 * Request parameters for getCountiesCountiesGet operation in CountiesApi.
 */
export interface CountiesApiGetCountiesCountiesGetRequest {
    readonly name?: string | null

    readonly fipsCode?: string | null
}

/**
 * Request parameters for getCountyByFipsCountiesFipsCodeGet operation in CountiesApi.
 */
export interface CountiesApiGetCountyByFipsCountiesFipsCodeGetRequest {
    readonly fipsCode: string
}

/**
 * Request parameters for getDebtByCountyFipsCountiesFipsCodeDebtGet operation in CountiesApi.
 */
export interface CountiesApiGetDebtByCountyFipsCountiesFipsCodeDebtGetRequest {
    readonly fipsCode: string
}

/**
 * CountiesApi - object-oriented interface
 */
export class CountiesApi extends BaseAPI implements CountiesApiInterface {
    /**
     * Get all counties information
     * @summary Get all counties
     * @param {CountiesApiGetCountiesCountiesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountiesCountiesGet(requestParameters: CountiesApiGetCountiesCountiesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return CountiesApiFp(this.configuration).getCountiesCountiesGet(requestParameters.name, requestParameters.fipsCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get specific county details
     * @summary Get county details
     * @param {CountiesApiGetCountyByFipsCountiesFipsCodeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountyByFipsCountiesFipsCodeGet(requestParameters: CountiesApiGetCountyByFipsCountiesFipsCodeGetRequest, options?: RawAxiosRequestConfig) {
        return CountiesApiFp(this.configuration).getCountyByFipsCountiesFipsCodeGet(requestParameters.fipsCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get specific county debt details
     * @summary Get county debt
     * @param {CountiesApiGetDebtByCountyFipsCountiesFipsCodeDebtGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDebtByCountyFipsCountiesFipsCodeDebtGet(requestParameters: CountiesApiGetDebtByCountyFipsCountiesFipsCodeDebtGetRequest, options?: RawAxiosRequestConfig) {
        return CountiesApiFp(this.configuration).getDebtByCountyFipsCountiesFipsCodeDebtGet(requestParameters.fipsCode, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DebtsApi - axios parameter creator
 */
export const DebtsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all county debt details
         * @summary Get all county debt
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountiesDebtDebtsCountiesGet: async (startDate?: string, endDate?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/debts/counties`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get county debt details
         * @summary Get county debt
         * @param {string} fipsCode 
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountyDebtDebtsCountiesFipsCodeGet: async (fipsCode: string, startDate?: string, endDate?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fipsCode' is not null or undefined
            assertParamExists('getCountyDebtDebtsCountiesFipsCodeGet', 'fipsCode', fipsCode)
            const localVarPath = `/debts/counties/{fips_code}`
                .replace(`{${"fips_code"}}`, encodeURIComponent(String(fipsCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all county debt details
         * @summary Get all county debt
         * @param {string | null} [county] 
         * @param {string | null} [state] 
         * @param {string | null} [fipsCode] 
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDebtsDebtsGet: async (county?: string | null, state?: string | null, fipsCode?: string | null, startDate?: string, endDate?: string | null, skip?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/debts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (county !== undefined) {
                localVarQueryParameter['county'] = county;
            }

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }

            if (fipsCode !== undefined) {
                localVarQueryParameter['fips_code'] = fipsCode;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get state debt details
         * @summary Get state debt
         * @param {string} stateCode 
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateDebtDebtsStatesStateCodeGet: async (stateCode: string, startDate?: string, endDate?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stateCode' is not null or undefined
            assertParamExists('getStateDebtDebtsStatesStateCodeGet', 'stateCode', stateCode)
            const localVarPath = `/debts/states/{state_code}`
                .replace(`{${"state_code"}}`, encodeURIComponent(String(stateCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all states debt details
         * @summary Get all states debt
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatesDebtDebtsStatesGet: async (startDate?: string, endDate?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/debts/states`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DebtsApi - functional programming interface
 */
export const DebtsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DebtsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all county debt details
         * @summary Get all county debt
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountiesDebtDebtsCountiesGet(startDate?: string, endDate?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CountyDebt>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountiesDebtDebtsCountiesGet(startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DebtsApi.getCountiesDebtDebtsCountiesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get county debt details
         * @summary Get county debt
         * @param {string} fipsCode 
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountyDebtDebtsCountiesFipsCodeGet(fipsCode: string, startDate?: string, endDate?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CountyDebt>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountyDebtDebtsCountiesFipsCodeGet(fipsCode, startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DebtsApi.getCountyDebtDebtsCountiesFipsCodeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all county debt details
         * @summary Get all county debt
         * @param {string | null} [county] 
         * @param {string | null} [state] 
         * @param {string | null} [fipsCode] 
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDebtsDebtsGet(county?: string | null, state?: string | null, fipsCode?: string | null, startDate?: string, endDate?: string | null, skip?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DebtExtended>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDebtsDebtsGet(county, state, fipsCode, startDate, endDate, skip, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DebtsApi.getDebtsDebtsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get state debt details
         * @summary Get state debt
         * @param {string} stateCode 
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStateDebtDebtsStatesStateCodeGet(stateCode: string, startDate?: string, endDate?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StateDebt>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStateDebtDebtsStatesStateCodeGet(stateCode, startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DebtsApi.getStateDebtDebtsStatesStateCodeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all states debt details
         * @summary Get all states debt
         * @param {string} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatesDebtDebtsStatesGet(startDate?: string, endDate?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<StateDebt>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatesDebtDebtsStatesGet(startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DebtsApi.getStatesDebtDebtsStatesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DebtsApi - factory interface
 */
export const DebtsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DebtsApiFp(configuration)
    return {
        /**
         * Get all county debt details
         * @summary Get all county debt
         * @param {DebtsApiGetCountiesDebtDebtsCountiesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountiesDebtDebtsCountiesGet(requestParameters: DebtsApiGetCountiesDebtDebtsCountiesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<CountyDebt>> {
            return localVarFp.getCountiesDebtDebtsCountiesGet(requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * Get county debt details
         * @summary Get county debt
         * @param {DebtsApiGetCountyDebtDebtsCountiesFipsCodeGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountyDebtDebtsCountiesFipsCodeGet(requestParameters: DebtsApiGetCountyDebtDebtsCountiesFipsCodeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<CountyDebt> {
            return localVarFp.getCountyDebtDebtsCountiesFipsCodeGet(requestParameters.fipsCode, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all county debt details
         * @summary Get all county debt
         * @param {DebtsApiGetDebtsDebtsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDebtsDebtsGet(requestParameters: DebtsApiGetDebtsDebtsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<DebtExtended>> {
            return localVarFp.getDebtsDebtsGet(requestParameters.county, requestParameters.state, requestParameters.fipsCode, requestParameters.startDate, requestParameters.endDate, requestParameters.skip, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Get state debt details
         * @summary Get state debt
         * @param {DebtsApiGetStateDebtDebtsStatesStateCodeGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateDebtDebtsStatesStateCodeGet(requestParameters: DebtsApiGetStateDebtDebtsStatesStateCodeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<StateDebt> {
            return localVarFp.getStateDebtDebtsStatesStateCodeGet(requestParameters.stateCode, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all states debt details
         * @summary Get all states debt
         * @param {DebtsApiGetStatesDebtDebtsStatesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatesDebtDebtsStatesGet(requestParameters: DebtsApiGetStatesDebtDebtsStatesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<StateDebt>> {
            return localVarFp.getStatesDebtDebtsStatesGet(requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DebtsApi - interface
 */
export interface DebtsApiInterface {
    /**
     * Get all county debt details
     * @summary Get all county debt
     * @param {DebtsApiGetCountiesDebtDebtsCountiesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCountiesDebtDebtsCountiesGet(requestParameters?: DebtsApiGetCountiesDebtDebtsCountiesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<CountyDebt>>;

    /**
     * Get county debt details
     * @summary Get county debt
     * @param {DebtsApiGetCountyDebtDebtsCountiesFipsCodeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCountyDebtDebtsCountiesFipsCodeGet(requestParameters: DebtsApiGetCountyDebtDebtsCountiesFipsCodeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<CountyDebt>;

    /**
     * Get all county debt details
     * @summary Get all county debt
     * @param {DebtsApiGetDebtsDebtsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDebtsDebtsGet(requestParameters?: DebtsApiGetDebtsDebtsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<DebtExtended>>;

    /**
     * Get state debt details
     * @summary Get state debt
     * @param {DebtsApiGetStateDebtDebtsStatesStateCodeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getStateDebtDebtsStatesStateCodeGet(requestParameters: DebtsApiGetStateDebtDebtsStatesStateCodeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<StateDebt>;

    /**
     * Get all states debt details
     * @summary Get all states debt
     * @param {DebtsApiGetStatesDebtDebtsStatesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getStatesDebtDebtsStatesGet(requestParameters?: DebtsApiGetStatesDebtDebtsStatesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<StateDebt>>;

}

/**
 * Request parameters for getCountiesDebtDebtsCountiesGet operation in DebtsApi.
 */
export interface DebtsApiGetCountiesDebtDebtsCountiesGetRequest {
    readonly startDate?: string

    readonly endDate?: string | null
}

/**
 * Request parameters for getCountyDebtDebtsCountiesFipsCodeGet operation in DebtsApi.
 */
export interface DebtsApiGetCountyDebtDebtsCountiesFipsCodeGetRequest {
    readonly fipsCode: string

    readonly startDate?: string

    readonly endDate?: string | null
}

/**
 * Request parameters for getDebtsDebtsGet operation in DebtsApi.
 */
export interface DebtsApiGetDebtsDebtsGetRequest {
    readonly county?: string | null

    readonly state?: string | null

    readonly fipsCode?: string | null

    readonly startDate?: string

    readonly endDate?: string | null

    readonly skip?: number

    readonly limit?: number
}

/**
 * Request parameters for getStateDebtDebtsStatesStateCodeGet operation in DebtsApi.
 */
export interface DebtsApiGetStateDebtDebtsStatesStateCodeGetRequest {
    readonly stateCode: string

    readonly startDate?: string

    readonly endDate?: string | null
}

/**
 * Request parameters for getStatesDebtDebtsStatesGet operation in DebtsApi.
 */
export interface DebtsApiGetStatesDebtDebtsStatesGetRequest {
    readonly startDate?: string

    readonly endDate?: string | null
}

/**
 * DebtsApi - object-oriented interface
 */
export class DebtsApi extends BaseAPI implements DebtsApiInterface {
    /**
     * Get all county debt details
     * @summary Get all county debt
     * @param {DebtsApiGetCountiesDebtDebtsCountiesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountiesDebtDebtsCountiesGet(requestParameters: DebtsApiGetCountiesDebtDebtsCountiesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return DebtsApiFp(this.configuration).getCountiesDebtDebtsCountiesGet(requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get county debt details
     * @summary Get county debt
     * @param {DebtsApiGetCountyDebtDebtsCountiesFipsCodeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountyDebtDebtsCountiesFipsCodeGet(requestParameters: DebtsApiGetCountyDebtDebtsCountiesFipsCodeGetRequest, options?: RawAxiosRequestConfig) {
        return DebtsApiFp(this.configuration).getCountyDebtDebtsCountiesFipsCodeGet(requestParameters.fipsCode, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all county debt details
     * @summary Get all county debt
     * @param {DebtsApiGetDebtsDebtsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDebtsDebtsGet(requestParameters: DebtsApiGetDebtsDebtsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return DebtsApiFp(this.configuration).getDebtsDebtsGet(requestParameters.county, requestParameters.state, requestParameters.fipsCode, requestParameters.startDate, requestParameters.endDate, requestParameters.skip, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get state debt details
     * @summary Get state debt
     * @param {DebtsApiGetStateDebtDebtsStatesStateCodeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStateDebtDebtsStatesStateCodeGet(requestParameters: DebtsApiGetStateDebtDebtsStatesStateCodeGetRequest, options?: RawAxiosRequestConfig) {
        return DebtsApiFp(this.configuration).getStateDebtDebtsStatesStateCodeGet(requestParameters.stateCode, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all states debt details
     * @summary Get all states debt
     * @param {DebtsApiGetStatesDebtDebtsStatesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStatesDebtDebtsStatesGet(requestParameters: DebtsApiGetStatesDebtDebtsStatesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return DebtsApiFp(this.configuration).getStatesDebtDebtsStatesGet(requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthCheckHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckHealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthCheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * 
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthCheckHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthCheckHealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * StatesApi - axios parameter creator
 */
export const StatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get specific state and its counties information by state code
         * @summary Get specific state and its counties
         * @param {string} stateCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateAndCountiesStatesStateCodeCountiesGet: async (stateCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stateCode' is not null or undefined
            assertParamExists('getStateAndCountiesStatesStateCodeCountiesGet', 'stateCode', stateCode)
            const localVarPath = `/states/{state_code}/counties`
                .replace(`{${"state_code"}}`, encodeURIComponent(String(stateCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get state information by state code
         * @summary Get specific state information
         * @param {string} stateCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateByCodeStatesStateCodeGet: async (stateCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stateCode' is not null or undefined
            assertParamExists('getStateByCodeStatesStateCodeGet', 'stateCode', stateCode)
            const localVarPath = `/states/{state_code}`
                .replace(`{${"state_code"}}`, encodeURIComponent(String(stateCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all state information or specific state info by query params
         * @summary Get state information
         * @param {string | null} [name] 
         * @param {string | null} [code] 
         * @param {string | null} [fipsCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatesStatesGet: async (name?: string | null, code?: string | null, fipsCode?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/states`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }

            if (fipsCode !== undefined) {
                localVarQueryParameter['fips_code'] = fipsCode;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatesApi - functional programming interface
 */
export const StatesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StatesApiAxiosParamCreator(configuration)
    return {
        /**
         * Get specific state and its counties information by state code
         * @summary Get specific state and its counties
         * @param {string} stateCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStateAndCountiesStatesStateCodeCountiesGet(stateCode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<County>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStateAndCountiesStatesStateCodeCountiesGet(stateCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatesApi.getStateAndCountiesStatesStateCodeCountiesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get state information by state code
         * @summary Get specific state information
         * @param {string} stateCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStateByCodeStatesStateCodeGet(stateCode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<State>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStateByCodeStatesStateCodeGet(stateCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatesApi.getStateByCodeStatesStateCodeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all state information or specific state info by query params
         * @summary Get state information
         * @param {string | null} [name] 
         * @param {string | null} [code] 
         * @param {string | null} [fipsCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatesStatesGet(name?: string | null, code?: string | null, fipsCode?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<State>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatesStatesGet(name, code, fipsCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatesApi.getStatesStatesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StatesApi - factory interface
 */
export const StatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StatesApiFp(configuration)
    return {
        /**
         * Get specific state and its counties information by state code
         * @summary Get specific state and its counties
         * @param {StatesApiGetStateAndCountiesStatesStateCodeCountiesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateAndCountiesStatesStateCodeCountiesGet(requestParameters: StatesApiGetStateAndCountiesStatesStateCodeCountiesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<County>> {
            return localVarFp.getStateAndCountiesStatesStateCodeCountiesGet(requestParameters.stateCode, options).then((request) => request(axios, basePath));
        },
        /**
         * Get state information by state code
         * @summary Get specific state information
         * @param {StatesApiGetStateByCodeStatesStateCodeGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateByCodeStatesStateCodeGet(requestParameters: StatesApiGetStateByCodeStatesStateCodeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<State> {
            return localVarFp.getStateByCodeStatesStateCodeGet(requestParameters.stateCode, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all state information or specific state info by query params
         * @summary Get state information
         * @param {StatesApiGetStatesStatesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatesStatesGet(requestParameters: StatesApiGetStatesStatesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<State>> {
            return localVarFp.getStatesStatesGet(requestParameters.name, requestParameters.code, requestParameters.fipsCode, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StatesApi - interface
 */
export interface StatesApiInterface {
    /**
     * Get specific state and its counties information by state code
     * @summary Get specific state and its counties
     * @param {StatesApiGetStateAndCountiesStatesStateCodeCountiesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getStateAndCountiesStatesStateCodeCountiesGet(requestParameters: StatesApiGetStateAndCountiesStatesStateCodeCountiesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<County>>;

    /**
     * Get state information by state code
     * @summary Get specific state information
     * @param {StatesApiGetStateByCodeStatesStateCodeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getStateByCodeStatesStateCodeGet(requestParameters: StatesApiGetStateByCodeStatesStateCodeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<State>;

    /**
     * Get all state information or specific state info by query params
     * @summary Get state information
     * @param {StatesApiGetStatesStatesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getStatesStatesGet(requestParameters?: StatesApiGetStatesStatesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<State>>;

}

/**
 * Request parameters for getStateAndCountiesStatesStateCodeCountiesGet operation in StatesApi.
 */
export interface StatesApiGetStateAndCountiesStatesStateCodeCountiesGetRequest {
    readonly stateCode: string
}

/**
 * Request parameters for getStateByCodeStatesStateCodeGet operation in StatesApi.
 */
export interface StatesApiGetStateByCodeStatesStateCodeGetRequest {
    readonly stateCode: string
}

/**
 * Request parameters for getStatesStatesGet operation in StatesApi.
 */
export interface StatesApiGetStatesStatesGetRequest {
    readonly name?: string | null

    readonly code?: string | null

    readonly fipsCode?: string | null
}

/**
 * StatesApi - object-oriented interface
 */
export class StatesApi extends BaseAPI implements StatesApiInterface {
    /**
     * Get specific state and its counties information by state code
     * @summary Get specific state and its counties
     * @param {StatesApiGetStateAndCountiesStatesStateCodeCountiesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStateAndCountiesStatesStateCodeCountiesGet(requestParameters: StatesApiGetStateAndCountiesStatesStateCodeCountiesGetRequest, options?: RawAxiosRequestConfig) {
        return StatesApiFp(this.configuration).getStateAndCountiesStatesStateCodeCountiesGet(requestParameters.stateCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get state information by state code
     * @summary Get specific state information
     * @param {StatesApiGetStateByCodeStatesStateCodeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStateByCodeStatesStateCodeGet(requestParameters: StatesApiGetStateByCodeStatesStateCodeGetRequest, options?: RawAxiosRequestConfig) {
        return StatesApiFp(this.configuration).getStateByCodeStatesStateCodeGet(requestParameters.stateCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all state information or specific state info by query params
     * @summary Get state information
     * @param {StatesApiGetStatesStatesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStatesStatesGet(requestParameters: StatesApiGetStatesStatesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return StatesApiFp(this.configuration).getStatesStatesGet(requestParameters.name, requestParameters.code, requestParameters.fipsCode, options).then((request) => request(this.axios, this.basePath));
    }
}



